### ISSUE TITLE
0.2 release checklist

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/templateeditor#55]
## Reason
- Release needed for "ticket X", "feature Y"

## QA
- [ ] Create release branch
- [ ] Create "$version Testplan"
- [ ] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label)
@VicDeo anything needed for QA to be specifically tested - please add here

## Marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

## Documentation
- [ ] Changes in the docs needed?

## Build & Marketplace release

- [ ] Bump version in info.xml
- [ ] Update CHANGELOG.md
- [ ] Create github tag for '$version'
- [ ] Build and sign tarball from github tag '$version'
- [ ] Upload to marketplace
- [ ] Rename QA milestone to '$version'
- [ ] Change CHANGELOG.md 'Unreleased' to '$version' and add a new 'Unreleased' section
- [ ] Create PR to merge changes back to `master`

**Comment by VicDeo** [comment]
@patrickjahns what's else needed from my side to proceed here?

**Comment by patrickjahns** [comment]
Looks good so far - product management (@pmaier1 ) and marketing need to put the app in the correct shape

**Comment by pmaier1** [comment]
Created PR for marketing stuff https://github.com/owncloud/templateeditor/pull/62

**Comment by pmaier1** [comment]
Marketing stuff merged!

**Comment by PVince81** [comment]
> unbundle from community tarballs

@patrickjahns is this done already ?

**Comment by davitol** [comment]
AFAIK not at least for stable 10 daily tarball
