### ISSUE TITLE
[For 10.0.9] Template Editor 0.3.1 release 

### ISSUE THREAD

**Issue by PVince81** [owncloud/templateeditor#72]
### Reason
- Release needed for https://github.com/owncloud/templateeditor/pull/69, https://github.com/owncloud/templateeditor/issues/70, https://github.com/owncloud/templateeditor/issues/71, https://github.com/owncloud/templateeditor/issues/73, mostly new editable templates

### QA
- [x] Create release branch @davitol https://github.com/owncloud/templateeditor/tree/release-0.3.1
- [x] Create "$version Testplan" @davitol https://github.com/owncloud/templateeditor/issues/78
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) @davitol

### Marketing
- [ ] Ping RocketChat channel #marketing - skipped ( @patrickjahns )
- [ ] Check/adapt info.xml stuff - skipped ( @patrickjahns )
- [ ] Check/adapt screenshot - skipped ( @patrickjahns )
- [ ] Blog post or other communication if applicable

### Documentation
- [ ] Changes in the docs needed?

### Build & Marketplace release

- [x] Bump version in info.xml - done via #80
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' done via #80
- [x] Create github tag for '$version' @patrickjahns
- [x] Build and sign tarball from github tag '$version' @patrickjahns
- [x] Upload to marketplace @patrickjahns
- [x] Send mail to release-coordination with link to this ticket and to the changelog @patrickjahns
- [x] Rename QA milestone to '$version' @patrickjahns
- [x] Add a new 'Unreleased' section in CHANGELOG.md @patrickjahns
- [x] Create PR to merge changes back to `master` @patrickjahns #82 

### Specifics

- Open tickets before QA can start
- Other specifics for app release

**Comment by PVince81** [comment]
PR for changelog: https://github.com/owncloud/templateeditor/pull/77
